development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mail_dev
  pool: 5
  username: root
  password: Focus_Mail
  host: 127.0.0.1

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mail_test
  pool: 5
  username: root
  password: Focus_Mail
  host: 127.0.0.1

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mail_dev
  pool: 5
  username: root
  password: Focus_Mail
  host: 127.0.0.1
